config {
  type: "incremental",
  schema: "hotel_search_gold",
  name: "arrival_daily",
  uniqueKey: ["city", "search_date", "arrival_date"],
  bigquery: {
    partitionBy: "search_date",
    clusterBy: ["city", "arrival_date"]
  },
  tags: ["gold", "trend"]
}

select
  city,
  search_date,
  arrival_date,
  sum(search_count) as search_count
from ${ref("fact_search_event")}
where city is not null
  and search_date is not null
  and arrival_date is not null
  ${when(incremental(), `
    and search_date >= date_sub(current_date(), interval 7 day)
  `, ``)}
group by city, search_date, arrival_date;
