config {
  type: "incremental",
  schema: "hotel_search_gold",
  name: "stay_length_daily",
  uniqueKey: ["city", "search_date", "length_of_stay"],
  bigquery: {
    partitionBy: "search_date",
    clusterBy: ["city", "length_of_stay"]
  },
  tags: ["gold", "trend"]
}

select
  city,
  search_date,
  length_of_stay,
  sum(search_count) as search_count
from ${ref("fact_search_event")}
where city is not null
  and search_date is not null
  and length_of_stay is not null
  ${when(incremental(), `
    and search_date >= date_sub(current_date(), interval 7 day)
  `, ``)}
group by city, search_date, length_of_stay;
